version: '3.8'

networks:
  public:
    name: public
    external: true

services:

    train_tune:
        deploy:
          replicas: 5
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 2h -D 2 --summary-interval 400 -g 1m -w 30m \
            --database-name binance_futures -l 18 -d 18 --leverage 2.0 \
            --offset-interval 24h --test-interval 24h --nb-steps 500 --max-negative-pnl -0.99 -m 960 --tune -s 1"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=0
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB
            - KERAS_DB


secrets:
  DB:
      external: true
  KERAS_DB:
      external: true
