version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    train_live:
        deploy:
          replicas: 0
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 12h -D 4 --summary-interval 4000 -g 2s -w 1m \
            --database-name binance_futures -l 64 -d 32 --leverage 2.0 \
            --offset-interval 8h --test-interval 8h --nb-steps 10000 \
            --max-negative-pnl -0.99 -m 1400 --tune -s 1 --cache --clear-dir"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=1
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB
            - KERAS_DB

    train_tune:
        deploy:
          replicas: 1
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 12h -D 4 --summary-interval 4000 -g 2s -w 1m \
            --database-name binance_futures -l 64 -d 32 --leverage 2.0 \
            --offset-interval 8h --test-interval 8h --nb-steps 10000 \
            --max-negative-pnl -0.99 -m 0 --tune -s 1 --cache --clear-dir"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=1
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB
            - KERAS_DB

secrets:
  DB:
      external: true
  KERAS_DB:
      external: true
