version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    train_live:
        deploy:
          replicas: 1
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
          ./examples/dqn_orderbook/run.py UNFIUSDT -i 8d -D 2 --summary-interval 400 -g 1m -w 30m \
          --database-name binance_futures -l 24 -d 30 --leverage 2.0 \
          --offset-interval 0h --test-interval 1d --nb-steps 36610 --max-negative-pnl -0.99 -m 200 -s 1"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=0
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB

    train_tune:
        deploy:
          replicas: 0
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 8d -D 2 --summary-interval 400 -g 1m -w 30m \
            --database-name binance_futures -l 24 -d 30 --leverage 2.0 \
            --offset-interval 2d --test-interval 2d --nb-steps 32266 --max-negative-pnl -0.99 -m 1533 --tune -s 1 --cache"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=1
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB


secrets:
  DB:
      external: true
