version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    train:
        deploy:
            replicas: 4
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py LRCUSDT -i 68h -D 5 --summary-interval 180 -g 30s -w 2m
            --database-name binance_futures -l 9 -d 46 --leverage 2.0
            --offset-interval 12h --test-interval 12h --nb-steps 29400 -m 410 -s 3 --max-negative-pnl -0.1
            --nb-steps-2 47600 --interval2 255m --cache"
        environment:
            - LOG_LEVEL=DEBUG
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB

    eval_agent:
      deploy:
        replicas: 0
      image: 'registry.rubercubic.com:5001/dqn-orderbook'
      volumes:
        - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
      command: bash -c "source ~/.bashrc &&
        ./examples/dqn_orderbook/eval_agent.py LRCUSDT --valid-interval 30m -m 1200"
      environment:
        - LOG_LEVEL=INFO
        - NVIDIA_VISIBLE_DEVICES=all
      networks:
        - public
      depends_on:
        - influxdb
        - redis
      secrets:
        - DB


secrets:
  DB:
      external: true
