version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    train_live:
        deploy:
          replicas: 1
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
          ./examples/dqn_orderbook/run.py UNFIUSDT -i 25h -D 2 --summary-interval 400 -g 30s -w 6m \
          --database-name binance_futures -l 7 -d 21 --leverage 2.0 \
          --offset-interval 0h --test-interval 9h --nb-steps 15472 --max-negative-pnl -0.99 -m 650 -s 1"
        environment:
            - LOG_LEVEL=DEBUG
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB

    train_tune:
        deploy:
          replicas: 0
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 25h -D 2 --summary-interval 400 -g 30s -w 6m \
            --database-name binance_futures -l 7 -d 21 --leverage 2.0 \
            --offset-interval 3h --test-interval 9h --nb-steps 15472 --max-negative-pnl -0.99 -m 650 --tune -s 1"
        environment:
            - LOG_LEVEL=DEBUG
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB


secrets:
  DB:
      external: true
