version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    train:
        deploy:
            replicas: 4
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py BAKEUSDT -i 21h -D 4 --summary-interval 30 -g 30s -w 2m
            --database-name binance_futures -l 22 -d 28 --leverage 10.0
            --offset-interval 90m --test-interval 90m --nb-steps 25000 -m 400 --cache"
        environment:
            - LOG_LEVEL=INFO
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB
secrets:
  DB:
      external: true
