version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    train:
        deploy:
            replicas: 1
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
          ./examples/dqn_orderbook/run.py LRCUSDT -i 2d -D 4 --summary-interval 400 -g 30s -w 6m \
          --database-name binance_futures -l 16 -d 42 --leverage 2.0 \
          --offset-interval 1d --test-interval 1d --nb-steps 500000 --max-negative-pnl -0.99 --cache -m 1200"
        environment:
            - LOG_LEVEL=DEBUG
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB

    eval_agent:
      deploy:
        replicas: 1
      image: 'registry.rubercubic.com:5001/dqn-orderbook'
      volumes:
        - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
      command: bash -c "source ~/.bashrc &&
        ./examples/dqn_orderbook/eval_agent.py LRCUSDT --valid-interval 4h -m 1200 -e 4m"
      environment:
        - LOG_LEVEL=INFO
        - NVIDIA_VISIBLE_DEVICES=all
      networks:
        - public
      depends_on:
        - influxdb
        - redis
      secrets:
        - DB


secrets:
  DB:
      external: true
