version: '3.8'

networks:
  public:
    name: public
    external: true

services:

    train_tune:
        deploy:
          replicas: 1
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 14h -D 3 --summary-interval 800 -g 30s -w 9m \
            --database-name binance_futures -l 88 -d 53 --leverage 2.0 \
            --offset-interval 6h --test-interval 9h --nb-steps 6415 --max-negative-pnl -0.99 -m 1775 --tune -s 1 --cache"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=0
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB


secrets:
  DB:
      external: true
