version: '3.8'

networks:
  public:
    name: public
    external: true

services:

    train_tune:
        deploy:
          replicas: 5
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 2d -D 3 --summary-interval 400 -g 10s -w 3m \
            --database-name binance_futures -l 24 -d 100 --leverage 2.0 \
            --offset-interval 6h --test-interval 12h --nb-steps 32266 --max-negative-pnl -0.99 -m 875 --tune -s 1"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=0
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB


secrets:
  DB:
      external: true
