version: '3.8'

networks:
  public:
    name: public
    external: true

services:

    train_tune:
        deploy:
          replicas: 1
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 8h -D 4 --summary-interval 200 -g 10s -w 3m \
            --database-name binance_futures -l 27 -d 27 --leverage 2.0 \
            --offset-interval 6h --test-interval 6h --nb-steps 5000 \
            --max-negative-pnl -0.99 -m 1200 --tune -s 1 --cache"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=0
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB
            - KERAS_DB


secrets:
  DB:
      external: true
  KERAS_DB:
      external: true
