version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    train:
        deploy:
            replicas: 4
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py LINAUSDT -i 90m -D 4 --summary-interval 30 -g 30s -w 2m
            --database-name binance_futures -l 22 -d 28 --leverage 10.0
            --offset-interval 0m --test-interval 120m --nb-steps 15000 -m 150 -s 3"
        environment:
            - LOG_LEVEL=INFO
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB

    eval_agent:
      deploy:
        replicas: 1
      image: 'registry.rubercubic.com:5001/dqn-orderbook'
      volumes:
        - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
      command: bash -c "source ~/.bashrc &&
        ./examples/dqn_orderbook/eval_agent.py LINAUSDT -m 150 --valid-interval 9m"
      environment:
        - LOG_LEVEL=DEBUG
        - NVIDIA_VISIBLE_DEVICES=all
      networks:
        - public
      depends_on:
        - influxdb
        - redis
      secrets:
        - DB


secrets:
  DB:
      external: true


#./examples/dqn_orderbook/run.py BAKEUSDT -i 21h -D 4 --summary-interval 30 -g 30s -w 2m \
#            --database-name binance_futures -l 22 -d 28 --leverage 10.0 \
#            --offset-interval 90m --test-interval 90m --nb-steps 26000 -m 400 -R
