version: '3.8'

networks:
  public:
    name: public
    external: true

services:

    train_tune:
        deploy:
          replicas: 1
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py UNFIUSDT -i 12h -D 4 --summary-interval 400 -g 2s -w 1m \
            --database-name binance_futures -l 64 -d 32 --leverage 2.0 \
            --offset-interval 4h --test-interval 4h --nb-steps 50000 \
            --max-negative-pnl -0.99 -m 470 --tune -s 1 --cache --clear-dir
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=0
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB
            - KERAS_DB


secrets:
  DB:
      external: true
  KERAS_DB:
      external: true
