version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    train:
        deploy:
            replicas: 6
        image: 'registry.rubercubic.com:5001/dqn-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc &&
            ./examples/dqn_orderbook/run.py LRCUSDT -i 41h -D 5 --summary-interval 20 -g 30s -w 2m
            --database-name binance_futures -l 12 -d 48 --leverage 2.0
            --offset-interval 2h --test-interval 4h --nb-steps 25700 -m 170 -s 3 --max-negative-pnl -0.02
            --nb-steps-2 5900 --interval2 345m --cache"
        environment:
            - LOG_LEVEL=INFO
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB

    eval_agent:
      deploy:
        replicas: 0
      image: 'registry.rubercubic.com:5001/dqn-orderbook'
      volumes:
        - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
      command: bash -c "source ~/.bashrc &&
        ./examples/dqn_orderbook/eval_agent.py LRCUSDT --valid-interval 30m -D 4 -l 2 -d 15 -m 120"
      environment:
        - LOG_LEVEL=DEBUG
        - NVIDIA_VISIBLE_DEVICES=all
      networks:
        - public
      depends_on:
        - influxdb
        - redis
      secrets:
        - DB


secrets:
  DB:
      external: true
